### ISSUE TITLE
Default to the most used project and task during the last week

### ISSUE THREAD

**Issue by ykarikos** [futurice/futuhours-ui#2]
It would be easier, when I create a new hour marking for a new day, if Futuhours could show the project and task in that project with most hours as the default selection. This feature was in the old Futuhours system and made hour input process smoother.

**Comment by phadej** [comment]
or recent? What if you change project? (that annoyed me in the previous hours *a lot*)

**Comment by ykarikos** [comment]
This can be mitigated by having small enough window for checking the "most hours". Maybe it would be feasible to check most hours during the last week of reported hours.

**Comment by ykarikos** [comment]
Also most recent would be good. In any case, the task seems to always default to the first one now.

**Comment by phadej** [comment]
And seems this issue is in the wrong repo.
